CREATE TABLE IF NOT EXISTS ai_model_catalog (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    model_key VARCHAR(255) NOT NULL COMMENT '模型唯一标识，如 gpt-4o / claude-4-sonnet / mj_imagine',
    display_name VARCHAR(255) DEFAULT NULL COMMENT '展示名称',
    provider VARCHAR(100) DEFAULT NULL COMMENT '供应商，如 openai/anthropic/google/qwen/deepseek/xai/midjourney',
    family VARCHAR(100) DEFAULT NULL COMMENT '模型家族，如 gpt/claude/gemini/qwen/mj/grok/o-series',
    model_group VARCHAR(100) DEFAULT NULL COMMENT '模型分组，如 llm/image/video/audio/embedding/realtime/search/coder',
    modality VARCHAR(100) DEFAULT NULL COMMENT '模态，如 text/image/audio/video/multimodal/text-vector',
    capability_tags JSON DEFAULT NULL COMMENT '能力标签JSON，如 ["thinking","search","vision"]',
    version_label VARCHAR(100) DEFAULT NULL COMMENT '版本标记，如 2025-08-07 / preview / latest / thinking',
    source_type VARCHAR(50) DEFAULT 'import' COMMENT '来源类型 manual/import/system',
    is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用 1启用 0停用',
    is_deprecated TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否废弃',
    sort_order INT NOT NULL DEFAULT 0 COMMENT '排序值',
    notes TEXT DEFAULT NULL COMMENT '备注',
    raw_meta JSON DEFAULT NULL COMMENT '原始扩展信息',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_model_catalog_model_key (model_key),
    KEY idx_ai_model_catalog_provider (provider),
    KEY idx_ai_model_catalog_family (family),
    KEY idx_ai_model_catalog_group (model_group),
    KEY idx_ai_model_catalog_active (is_active),
    KEY idx_ai_model_catalog_sort (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI模型目录表';
